services:
  mongodb:
    image: "mongo:latest"
    environment:
      - "MONGO_INITDB_DATABASE=bank"
      - "MONGO_INITDB_ROOT_PASSWORD=50UKnFmf6gFdpZiK"
      - "MONGO_INITDB_ROOT_USERNAME=tchoforwilson"
    ports:
      - "27017"
  auth_api:
    build: ./auth
    ports:
      - 9000:9000
